### PR TITLE
VCC-3451 VCC-3539 Add `toggleButtonIcon`; remove FontAwesome dependency for the demo page

### PR DESCRIPTION
**Pull request by stephymiehle**
## General

* Introduces `toggleButtonIcon`, an optional (and default `null`) way to easily add a custom text/HTML icon within the toggle button. This could be anything from a Unicode symbol to an inline `<svg>`, FontAwesome markup, an ``, etc.

## Demo Page

* Removes the CDN link for FontAwesome
* Uses a basic CSS triangle as the `default-icon` when no `toggleButtonIcon` is provided

### CODE REVIEW

**Review by Farsad — COMMENTED** [review]
@stephymiehle Do you think it would be beneficial to have a configuration option called 'dropdownSVG' with a default value of null? If this option is set, we can add it to the element. I believe that while we are updating the arrow, it would be worth making this change for better customizability.

**Comment by stephymiehle** [comment]
@Farsad Good idea! I updated this PR. I kept it more generic with `toggleButtonIcon` because we could support Unicode characters, icon framework markup, SVGs, images, etc.

**Review by Farsad — CHANGES_REQUESTED** [review]
@stephymiehle The changes made to the index.js file within the `transformSelectElement` method only apply when the Combobox is initialized from a `select` element. However, this is not mentioned in the documentation for the `toggleButtonIcon` option. If a user uses the legacy HTML initialization and sets an icon for the `toggleButtonIcon` config, nothing will happen. The optimal solution would be to allow users to set these options in both cases. Then, during initialization, you should check and add them to the toggle element using HTML.
The SVG element in your HTML sample on the demo appears to be redundant and should be removed while the svg icon is set from the config.

**Comment by stephymiehle** [comment]
Edit: I goofed 🤪 Updating the comment for posterity.

If a `new Combobo({ toggleButtonIcon: '🔽' })` is initiated without specifying an input/select, the custom icon will "take over" on all other Combobo on the page that have a default icon (no custom icon set). The Combobo **must** have an input/select set!

**Review by Farsad — APPROVED** [review]

**Review by vicaraya — APPROVED** [review]

**Pull request merged**
